### ISSUE TITLE
[BUG] panic: runtime error

### ISSUE THREAD

**Issue by evilangelmd** [denverquane/automuteus#237] opened 2020-11-09 08:54 UTC
Hi. i'm using linux version of bot, self-hosted.

using latest build.

in console had this message before shutting down:

2020/11/07 13:59:15 HTTP 503 Service Unavailable, upstream connect error or disconnect/reset before headers. reset reason: overflow
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0x8478676]

goroutine 152937 [running]:
github.com/denverquane/amongusdiscord/discord.guildMemberUpdate(0xa8983c0, 0xac1ea40, 0x12, 0xaaeebb0, 0x9, 0xac1eac0, 0x12, 0xaaeebe0, 0x9, 0xaaeebbc, ...)
	/home/runner/work/automuteus/automuteus/discord/helpers.go:32 +0x3c6
github.com/denverquane/amongusdiscord/discord.muteWorker(0xa8983c0, 0xaaef1c0, 0xac1ea40, 0x12, 0xaaeebb0, 0x9, 0xac1eac0, 0x12, 0xaaeebe0, 0x9, ...)
	/home/runner/work/automuteus/automuteus/discord/voice.go:205 +0x2e
created by github.com/denverquane/amongusdiscord/discord.(*Bot).handleTrackedMembers
	/home/runner/work/automuteus/automuteus/discord/voice.go:196 +0xa59

On server have 2 bots all bots have admin privileges.

**Comment by denverquane** [comment] 2021-01-04 16:43
This was caused by an inability to connect to discord, and a resulting null pointer reference. Should be fixed in latest releases; more stringent checking of the pointers in this code path

**Closed by denverquane** 2021-01-04 16:43 UTC
