### ISSUE TITLE
Error with capture link

### ISSUE THREAD

**Issue by felipemolski** [denverquane/automuteus#119] opened 2020-10-08 05:07 UTC
Capture link did not work automatically, entered manually in Among Us Capture
Previous version with manual code insertion worked normally
I renamed the bot and removed the spaces, but it still doesn't work

![1](https://user-images.githubusercontent.com/13579495/95417015-67c1a900-090a-11eb-8174-b5184ed71bd7.PNG)
![2](https://user-images.githubusercontent.com/13579495/95417022-68f2d600-090a-11eb-88f0-b165b5e71351.PNG)
![3](https://user-images.githubusercontent.com/13579495/95417023-68f2d600-090a-11eb-8c15-30b1a8646b2e.PNG)
![4](https://user-images.githubusercontent.com/13579495/95417024-698b6c80-090a-11eb-8ec4-8039d07c2456.PNG)

**Comment by Plysm** [comment] 2020-10-08 07:46
I am also having this issue where the implementation of URI is not working and even if I manually input the information the bot still displays that no capture is linked. Here is a video I made showing the issue. https://youtu.be/5ChO2fnEOjM

**Comment by Stenlan** [comment] 2020-10-08 09:49
Thanks @Plysm for the clear video! The fact that manual linking doesn't work is because you can only paste 6 of the 8 characters into the connect code. This will be fixed, but automatic linking should just work as well. I think that both of you have an antivirus blocking pipe communication. Could either of you verify this by either making an exception in your AV, or clicking the link while the capture is _not_ yet running?

PS @felipemolski the URL field should only contain the host URL, not our formatted link. But currently, you can't manually connect anyway. So please try the above

**Comment by CarterBrehm** [comment] 2020-10-08 13:58
Just checking in to say that the automatic linking doesn't work at all. The discord bot sends me a URL, but clicking it does nothing. And since I can't type in the capture code manually, the only way to get it to work currently is to host it locally and use http://localhost:8123. Running on Windows 10. I did check the "Default apps by protocol" section of Windows settings to see if I could find the aucapture:// url there and it wasn't. I can provide more debug information if necessary.

**Comment by Stenlan** [comment] 2020-10-08 14:20
@CarterBrehm did you run the capture at least once before trying this? The capture needs to have run once to associate itself with the aucapture:// protocol

**Comment by CarterBrehm** [comment] 2020-10-08 14:55
@Stenlan I did. In fact, I even tried while the capture program was running and not running. When the program isn't running and I click the link, it loads for a fraction of a second and nothing happens. When the program is already open, nothing happens at all. The same thing happens when I copy the link into Firefox and open it from there.

**Comment by Plysm** [comment] 2020-10-08 20:55
I fixed my issue by simply running the capture program as an administrator. There is another issue though for those running the bot via Heroku as when you get the link the port is appended onto the end and must be removed to connect other than that this works flawlessly now.

**Comment by felipemolski** [comment] 2020-10-08 21:07
> I fixed my issue by simply running the capture program as an administrator. There is another issue though for those running the bot via Heroku as when you get the link the port is appended onto the end and must be removed to connect other than that this works flawlessly now.

I ran the capture program as an administrator and this time the link was captured, strange because yesterday I tried it too and it just didn't work. thanks for the feedback

**Comment by CarterBrehm** [comment] 2020-10-08 22:11
Can confirm, my issue was caused by #121. Hosting the bot on my own computer works immediately and the URL scheme opens the application as it should.

**Comment by jmengelle** [comment] 2020-10-09 19:45
Tried with both admin mode et standard mode : it works. 
But at first i didn't noticed the private message from the bot, and i didn't understood the message as "DM" was not clear to me. 
You should update the readme i guess.

**Comment by GuavaKhan** [comment] 2020-10-12 01:13
Related to this: 

I would recommend adding a version check to the connection / handshake that the capture software does with the bot. Took about an hour to figure out that even though the capture was connecting to the bot successfully, the connect code the bot gave me was 2 characters longer than my capture software allowed. I was stuck wondering why the capture software showed a green (valid) connection, but the discord bot said the capture software was not connected! A version mismatch warning would speed up troubleshooting.

**Comment by Inaruslynx** [comment] 2020-10-13 05:39
So this is what I discovered when I had a similar issue. I'm not sure if this would fall under this same ticket.

I was first launching the bot then the capture manually as the README.md suggests. I would then host a game. I would verify that the capture was working. Then I would issue .au n to the bot. The bot wasn't connected to capture so it DM'd me with the link. I'd then click the link, but I already had a capture open and didn't know I should not have it open yet. All I would see is that discord wasn't showing any data on the bot from the capture.

After a while, I came here and saw I wasn't supposed to have capture already open due to this ticket. This is exactly the opposite of what the README.md says to do.

I'm assuming that the README wasn't updated since the auto connect feature with DM has been added. I would recommend someone edit [](https://github.com/denverquane/amongusdiscord#easiest) to reflect new ways of connecting bot and capture both manually and automatically.

**Comment by ShawnHardwick** [comment] 2020-10-15 03:09
I can concur with that @Inaruslynx said. While I enjoy the URL opening the capture software directly with the session linked, I think that if the capture software is already open that it should also link. This used to be the default behavior so I'm not sure if this a bug or intended feature.

The software gets better and better. Keep up the great work :)

Capture version: 2.3.4
Bot version: 2.3.2

**Closed** 2020-12-22 08:28 UTC
